#!/bin/bash
# UX Preview - Wizualizacja pTTY v0.2

clear

echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║                       pTTY v0.2 - UX Preview                              ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
echo ""

# 1. Status Bar Preview
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. STATUS BAR (dolny pasek w tmux)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "┌─────────────────────────────────────────────────────────────────────────┐"
echo "│  [Your terminal content here]                                           │"
echo "│                                                                          │"
echo "│  zentala@vps:~$ ls                                                       │"
echo "│  src/  docs/  tests/                                                     │"
echo "│  zentala@vps:~$                                                          │"
echo "│                                                                          │"
echo "└─────────────────────────────────────────────────────────────────────────┘"
# Colored status bar simulation
echo -ne "\033[48;5;22m\033[38;5;15m\033[1m F1:●web \033[0m"
echo -ne "\033[48;5;22m\033[38;5;15m F2:●api \033[0m "
echo -ne "\033[48;5;235m\033[38;5;244m F3:○log \033[0m "
echo -ne "\033[48;5;22m\033[38;5;15m F4:●db \033[0m "
echo -ne "\033[48;5;235m\033[38;5;196m F5:✖task \033[0m "
echo -ne "\033[48;5;235m\033[38;5;244m F6:○ F7:○ F8:○ F9:○ F10:○\033[0m "
echo -e "\033[48;5;234m\033[38;5;244m zentala@vps 15:21 \033[0m"
echo ""
echo "Legenda:"
echo "  ● (zielone tło) = Aktywna konsola"
echo "  ○ (szare tło)   = Nieaktywna konsola"
echo "  ✖ (czerwone)    = Crashed konsola"
echo "  Pogrubione      = Bieżąca konsola"
echo ""
echo "Naciśnij Enter aby zobaczyć następny ekran..."
read -r

clear

# 2. F11 Manager Preview
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2. F11 MANAGER (pełny ekran, Ctrl+F11)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "┌───────────────────────────────────────────────────────────┐"
echo "│                    Console Manager                        │"
echo "├───────────────────────────────────────────────────────────┤"
echo "│                                                           │"
echo "│  1. console-1 (web)        ● Active      2d 12h          │"
echo "│  2. console-2 (api)        ● Active      2d 12h          │"
echo "│  3. console-3 (log)        ○ Inactive    2d 12h          │"
echo "│  4. console-4 (db)         ● Active      2d 12h          │"
echo "│  5. console-5 (tasks)      ✖ Crashed     2h 34m          │"
echo "│  6. console-6              ○ Suspended   -                │"
echo "│  7. console-7              ○ Suspended   -                │"
echo "│  8. console-8              ○ Suspended   -                │"
echo "│  9. console-9              ○ Suspended   -                │"
echo "│ 10. console-10             ○ Suspended   -                │"
echo "│                                                           │"
echo "│  Actions:                                                 │"
echo "│  [1-9,0] Switch   [R] Restart   [K] Kill   [A] Activate  │"
echo "│  [ESC] Close                                              │"
echo "│                                                           │"
echo "└───────────────────────────────────────────────────────────┘"
echo ""
echo "Co możesz zrobić:"
echo "  • Naciśnij 5 → przełącz do console-5 (crashed)"
echo "  • Naciśnij R → restart bieżącej konsoli"
echo "  • Naciśnij K → kill konsoli (z potwierdzeniem)"
echo "  • Naciśnij A → aktywuj zawieszoną konsolę"
echo "  • ESC → zamknij manager"
echo ""
echo "Naciśnij Enter aby zobaczyć następny ekran..."
read -r

clear

# 3. F12 Help Preview
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3. F12 HELP (pełny ekran, Ctrl+F12)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│               Keyboard Shortcuts Reference                  │"
echo "├─────────────────────────────────────────────────────────────┤"
echo "│                                                             │"
echo "│  CONSOLE SWITCHING                                          │"
echo "│  ─────────────────                                          │"
echo "│  Ctrl+F1-F5     Switch to active console (F1-F5)           │"
echo "│  Ctrl+F6-F10    Activate/switch to console (F6-F10)        │"
echo "│  Ctrl+F11       Open Manager (console management)          │"
echo "│  Ctrl+F12       Show this help                             │"
echo "│                                                             │"
echo "│  NAVIGATION                                                 │"
echo "│  ──────────                                                 │"
echo "│  Ctrl+Left      Previous console                           │"
echo "│  Ctrl+Right     Next console                               │"
echo "│  Ctrl+Esc       Detach (leave console safely)              │"
echo "│                                                             │"
echo "│  ACTIONS                                                    │"
echo "│  ───────                                                    │"
echo "│  Ctrl+R         Restart current console                    │"
echo "│  Ctrl+Del       Restart current console                    │"
echo "│  Ctrl+Alt+R     Reset terminal (clear + reset)             │"
echo "│                                                             │"
echo "│  HELP & SHORTCUTS                                           │"
echo "│  ────────────────                                           │"
echo "│  Ctrl+H         Quick shortcuts popup                      │"
echo "│  Ctrl+?         Quick shortcuts popup                      │"
echo "│                                                             │"
echo "│  Press Esc or Ctrl+F12 to close                            │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "Naciśnij Enter aby zobaczyć następny ekran..."
read -r

clear

# 4. Safe Exit Preview
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4. SAFE EXIT (popup gdy wpiszesz 'exit')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "zentala@vps:~$ exit"
echo ""
echo "┌───────────────────────────────────────────────────────────┐"
echo "│                                                           │"
echo "│  You're in a persistent tmux session \"console-1\".        │"
echo "│                                                           │"
echo "│  What do you want to do?                                 │"
echo "│                                                           │"
echo "│  • Press ENTER to detach safely                          │"
echo "│    (session continues running in background)             │"
echo "│                                                           │"
echo "│  • Press ESC or Ctrl+C to stay in session                │"
echo "│                                                           │"
echo "│  • Press SHIFT+Y to restart console (DANGEROUS!)         │"
echo "│    (kills all processes and creates new session)         │"
echo "│                                                           │"
echo "│  Your choice: _                                          │"
echo "│                                                           │"
echo "└───────────────────────────────────────────────────────────┘"
echo ""
echo "Interakcja:"
echo "  • ENTER → detach (bezpieczne, sesja działa dalej)"
echo "  • ESC/Ctrl+C → anuluj, zostań w sesji"
echo "  • SHIFT+Y → restart konsoli (niebezpieczne!)"
echo "  • małe 'y' → błąd \"Use SHIFT+Y\" (ochrona)"
echo ""
echo "Naciśnij Enter aby zobaczyć następny ekran..."
read -r

clear

# 5. Ctrl+H Quick Help Preview
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5. CTRL+H QUICK SHORTCUTS (mały popup)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "zentala@vps:~$ [Ctrl+H naciśnięte]"
echo ""
echo "                  ┌─────────────────────────────────┐"
echo "                  │     Quick Shortcuts             │"
echo "                  ├─────────────────────────────────┤"
echo "                  │  Ctrl+F1-10   Switch console    │"
echo "                  │  Ctrl+F11     Manager           │"
echo "                  │  Ctrl+F12     Full help         │"
echo "                  │  Ctrl+R       Restart           │"
echo "                  │  Ctrl+Esc     Detach            │"
echo "                  │                                 │"
echo "                  │  Press any key to close         │"
echo "                  └─────────────────────────────────┘"
echo ""
echo "  • Kompaktowy popup z najważniejszymi skrótami"
echo "  • Nie zasłania pracy"
echo "  • Zamyka się dowolnym klawiszem"
echo ""
echo "Naciśnij Enter aby zobaczyć podsumowanie..."
read -r

clear

# Summary
echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║                    UX REVIEW SUMMARY                                      ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 UX SCORES:"
echo ""
echo "  Status Bar:           ████████░░ 9/10  (excellent visibility)"
echo "  F11 Manager:          ████████░░ 9/10  (clear UI, safe actions)"
echo "  F12 Help:             ████████░░ 8/10  (good organization)"
echo "  Safe Exit:            ██████████ 10/10 (perfect protection!)"
echo "  Keyboard Shortcuts:   ████████░░ 9/10  (consistent & intuitive)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 DECISION: 🟢 GO - Approved for implementation!"
echo ""
echo "✅ STRENGTHS:"
echo "  • Natychmiastowa widoczność stanu konsol"
echo "  • Intuicyjne ikony (●○✖) i kolory"
echo "  • Bezpieczne akcje (ESC zawsze anuluje)"
echo "  • Jasne komunikaty i wyjaśnienia"
echo "  • Spójne skróty klawiszowe (Ctrl+ prefix)"
echo "  • Ochrona przed przypadkowym restart/kill"
echo ""
echo "⚠️  ISSUES FOUND (non-blocking):"
echo "  • UX-001: Kill potrzebuje potwierdzenia (v0.2.1)"
echo "  • UX-002: Test na 80-kolumnowym terminalu (v0.2.1)"
echo "  • UX-003: Dodaj przykłady do Help (v0.3)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🟢 NEXT STEPS:"
echo "  • Tasks 001-004 APPROVED do implementacji"
echo "  • Zacznij od Task 001 (State Management)"
echo "  • Następnie Task 002 (UI Components)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Gotowy do implementacji? Wpisz: 'Zacznijmy Task 001'"
echo ""
